FROM --platform=linux/amd64 docker.io/library/python:3.11-slim
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*
RUN groupadd -r user && useradd -m --no-log-init -r -g user user
USER user
WORKDIR /opt/app
RUN python -m pip install --user --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu126 && \
    python -m pip install --user --no-cache-dir ultralytics opencv-python-headless
COPY --chown=user:user resources /opt/app/resources
COPY --chown=user:user inference_v5.py /opt/app/inference.py
ENTRYPOINT ["python", "inference.py"]
