"""SurgVU 2026 Category 1 — v5 容器（2026-09-02）：與 v1 同推論邏輯，權重來源改為
  1) GC Algorithm Model tarball 掛載點 /opt/ml/model/**/*.pt（優先；免重傳 3.7GB image）
  2) 否則 /opt/app/resources/best.pt（隨 image 打包的 s1 保底權重）
輸出：逐幀偵測框、原生像素座標、真實信心值。
T4 預算：YOLO11-l FP16 ~40ms/幀，687 幀 << 10 分鐘。
"""
from pathlib import Path
import json

import cv2
import torch
from ultralytics import YOLO

INPUT_PATH = Path("/input")
OUTPUT_PATH = Path("/output")
MODEL_DIR = Path("/opt/ml/model")
FALLBACK_WEIGHTS = Path("/opt/app/resources/best.pt")


def resolve_weights():
    """model tarball 優先（任意子目錄下的 *.pt，多個時取檔名排序最後者，如 best.pt > allgt_last.pt 需自行命名）。"""
    cands = sorted(MODEL_DIR.rglob("*.pt")) if MODEL_DIR.exists() else []
    cands = [c for c in cands if c.is_file() and c.stat().st_size > 1_000_000]
    if cands:
        print("weights from model tarball:", [str(c) for c in cands])
        return cands[-1]
    print("weights fallback:", FALLBACK_WEIGHTS)
    return FALLBACK_WEIGHTS

CONF_MIN = 0.05   # maxDets=[5,10,100] 寬鬆 → 低閾多留框有利 AP
IMG_SZ = 640


def run():
    inputs = json.loads((INPUT_PATH / "inputs.json").read_text())
    def slug_of(sv):
        meta = sv.get("socket") or sv.get("interface") or {}
        return meta.get("slug", "")
    print("sockets:", sorted(slug_of(sv) for sv in inputs))

    device = 0 if torch.cuda.is_available() else "cpu"
    print("device:", device, torch.cuda.get_device_name(0) if device == 0 else "")
    WEIGHTS = resolve_weights()
    model = YOLO(str(WEIGHTS))
    print("loaded:", WEIGHTS, "| names:", list(model.names.values()))
    names = model.names  # id -> class name（訓練時已用 eval vocabulary 底線格式）

    video_path = INPUT_PATH / "endoscopic-robotic-surgery-video.mp4"
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"cannot open video: {video_path}")

    all_boxes = []
    slice_nr = 0
    batch_frames, batch_ids = [], []

    def flush():
        nonlocal batch_frames, batch_ids
        if not batch_frames:
            return
        results = model.predict(batch_frames, conf=CONF_MIN, imgsz=IMG_SZ,
                                device=device, half=(device == 0), verbose=False)
        for fid, r in zip(batch_ids, results):
            for b in r.boxes:
                x1, y1, x2, y2 = b.xyxy[0].tolist()
                all_boxes.append({
                    "name": f"slice_nr_{fid}_{names[int(b.cls)]}",
                    "corners": [[x1, y1, 0.5], [x2, y1, 0.5], [x2, y2, 0.5], [x1, y2, 0.5]],
                    "probability": round(float(b.conf), 5),
                })
        batch_frames, batch_ids = [], []

    while True:
        ok, frame = cap.read()
        if not ok:
            break
        batch_frames.append(frame)
        batch_ids.append(slice_nr)
        slice_nr += 1
        if len(batch_frames) == 16:
            flush()
    flush()
    cap.release()
    print(f"processed {slice_nr} frames, {len(all_boxes)} boxes")

    output = {
        "type": "Multiple 2D bounding boxes",
        "boxes": all_boxes,
        "version": {"major": 1, "minor": 0},
    }
    (OUTPUT_PATH / "surgical-tools.json").write_text(json.dumps(output))
    print("json file generated by the submission container")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
